Updated spacing

diff --git a/.github/workflows/prevent-pr-master.yml b/.github/workflows/prevent-pr-master.yml
--- a/.github/workflows/prevent-pr-master.yml
+++ b/.github/workflows/prevent-pr-master.yml
@@ -15,7 +15,7 @@ jobs:
       - uses: actions/checkout@v1
       - name: Allowed to merge to master
         run: |
-          echo "::error::
-            *****
-            Only release branch is allowed to merge to master";
-            exit 1;
+          echo "";
+          echo "*****";
+          echo"::error::Only release branch is allowed to merge to master";
+          exit 1;
